local module = {}
-- older Enviorment.luau 
module.Icons = {
	Topbar_Minimize = 	"rbxassetid://5034768003",
	Topbar_Maximize = "rbxassetid://5060023708",
	Topbar_Close = "rbxassetid://5054663650"
} 
module.Topbar_Accent = Color3.fromRGB(38,38,38)
module.BackgroundColor = Color3.fromRGB(43,43,43)
module.MoreAccent = Color3.fromRGB(24,24,24)
module.SelectionColor = Color3.fromRGB(12, 91, 176)
module.Explorer_IndentSeparation = 20 --18
module.Window_ShowTitleOnMiddle = true
module.Window_CornerRadius = 0
module.Window_AnimationTime = 0.2
module.IconPack = "NewDark"
module.BackgroundTransparency = 0.2
return module
